import type { Brand, Memory } from "./types";

export const BRANDS: Brand[] = [
  { id: "kopi", name: "Kopi Kulture", category: "Specialty coffee", tone: "warm, witty, ritual-led" },
  { id: "biryani", name: "Biryani Bhai", category: "Biryani restaurant", tone: "loud, hungry, family-first" },
  { id: "sari", name: "Sari & Sole", category: "Fashion", tone: "elegant, modern, festive" },
];

type SeedMemory = Omit<Memory, "id" | "createdAt">;

const SEED: SeedMemory[] = [
  // Kopi Kulture
  {
    brandId: "kopi",
    hook: "Light the whole street, one cup.",
    body: "Diwali mornings start with a filter pour. Free second cup for the family.",
    audience: "18-34, tier-2 cities",
    channel: "Instagram Reels",
    festival: "Diwali",
    goal: "First-order lift",
    predictedCtr: 4.1,
    actualCtr: 4.9,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "kopi",
    hook: "Flat 12% off every cup, no strings.",
    body: "Diwali sale. Use code SAVE12 on all beverages.",
    audience: "18-34, tier-2 cities",
    channel: "Instagram Reels",
    festival: "Diwali",
    goal: "First-order lift",
    predictedCtr: 3.4,
    actualCtr: 0.9,
    outcome: "flop",
    source: "own",
    year: 2025,
  },
  {
    brandId: "kopi",
    hook: "First harvest, first pour.",
    body: "Sankranti belongs to the farmers. This week's beans are theirs too.",
    audience: "25-40, Hyderabad offices",
    channel: "WhatsApp",
    festival: "Sankranti",
    goal: "Repeat orders",
    predictedCtr: 3.0,
    actualCtr: 3.6,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "kopi",
    hook: "Second innings needs a second cup.",
    body: "IPL late nights, cold brew on 20-minute delivery.",
    audience: "18-30, cricket fans",
    channel: "YouTube Shorts",
    festival: "IPL",
    goal: "App installs",
    predictedCtr: 2.6,
    actualCtr: 2.2,
    outcome: "flop",
    source: "own",
    year: 2025,
  },
  {
    brandId: "kopi",
    hook: "Brewed near the Bonalu route.",
    body: "Free water and filter coffee for anyone walking the procession.",
    audience: "all ages, Secunderabad",
    channel: "Outdoor",
    festival: "Bonalu",
    goal: "Footfall",
    predictedCtr: 3.2,
    actualCtr: 4.1,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "kopi",
    hook: "Buy one latte, get one free — today only.",
    body: "Rival chain's Diwali push on Reels.",
    audience: "18-34, tier-2 cities",
    channel: "Instagram Reels",
    festival: "Diwali",
    goal: "First-order lift",
    predictedCtr: null,
    actualCtr: 4.4,
    outcome: "win",
    source: "competitor",
    competitor: "Brew Bros",
    year: 2025,
  },

  // Biryani Bhai
  {
    brandId: "biryani",
    hook: "Your table, our biryani, their gossip.",
    body: "Eid dawats come home in a 6-person handi.",
    audience: "families, 25-50, Hyderabad",
    channel: "WhatsApp",
    festival: "Eid",
    goal: "Footfall",
    predictedCtr: 4.5,
    actualCtr: 5.2,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "biryani",
    hook: "Ugadi thali, biryani included.",
    body: "Six tastes of Ugadi, plus the one everyone actually came for.",
    audience: "families, 25-50, Hyderabad",
    channel: "Instagram Reels",
    festival: "Ugadi",
    goal: "Footfall",
    predictedCtr: 3.4,
    actualCtr: 3.9,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "biryani",
    hook: "Cheapest biryani in the city.",
    body: "₹99 mini biryani, limited stock.",
    audience: "students, 18-24",
    channel: "X (Twitter)",
    festival: "No festival",
    goal: "First-order lift",
    predictedCtr: 2.8,
    actualCtr: 1.0,
    outcome: "flop",
    source: "own",
    year: 2025,
  },
  {
    brandId: "biryani",
    hook: "Every wicket, one more plate.",
    body: "IPL match nights: family bucket at match-start price.",
    audience: "18-30, cricket fans",
    channel: "YouTube Shorts",
    festival: "IPL",
    goal: "Repeat orders",
    predictedCtr: 3.9,
    actualCtr: 4.6,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "biryani",
    hook: "Free delivery on every IPL order.",
    body: "Rival's match-night campaign.",
    audience: "18-30, cricket fans",
    channel: "YouTube Shorts",
    festival: "IPL",
    goal: "Repeat orders",
    predictedCtr: null,
    actualCtr: 4.8,
    outcome: "win",
    source: "competitor",
    competitor: "Handi House",
    year: 2025,
  },

  // Sari & Sole
  {
    brandId: "sari",
    hook: "The drape you'll be asked about all night.",
    body: "Diwali drop: 14 handwoven weaves, 40 pieces each.",
    audience: "women 24-40, metros",
    channel: "Instagram Reels",
    festival: "Diwali",
    goal: "First-order lift",
    predictedCtr: 3.8,
    actualCtr: 4.4,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "sari",
    hook: "Colour your feed, not your shirt.",
    body: "Holi whites, stain-safe fabric.",
    audience: "women 24-40, metros",
    channel: "X (Twitter)",
    festival: "Holi",
    goal: "Awareness",
    predictedCtr: 2.9,
    actualCtr: 1.1,
    outcome: "flop",
    source: "own",
    year: 2025,
  },
  {
    brandId: "sari",
    hook: "New year, new nine yards.",
    body: "Ugadi capsule in raw mango yellow.",
    audience: "women 24-40, Telugu states",
    channel: "Instagram Reels",
    festival: "Ugadi",
    goal: "Awareness",
    predictedCtr: 3.1,
    actualCtr: 3.5,
    outcome: "win",
    source: "own",
    year: 2025,
  },
  {
    brandId: "sari",
    hook: "End of season, everything must go.",
    body: "Sankranti clearance, up to 60% off.",
    audience: "women 24-40, Telugu states",
    channel: "Google Search",
    festival: "Sankranti",
    goal: "First-order lift",
    predictedCtr: 2.4,
    actualCtr: 1.3,
    outcome: "flop",
    source: "own",
    year: 2025,
  },
  {
    brandId: "sari",
    hook: "Influencer-led Diwali try-on haul.",
    body: "Rival brand's creator campaign.",
    audience: "women 24-40, metros",
    channel: "Instagram Reels",
    festival: "Diwali",
    goal: "Awareness",
    predictedCtr: null,
    actualCtr: 5.0,
    outcome: "win",
    source: "competitor",
    competitor: "Zari Co.",
    year: 2025,
  },
];

export function seedMemories(): Memory[] {
  const base = Date.now() - SEED.length * 86_400_000;
  return SEED.map((m, i) => ({
    ...m,
    id: `seed-${i}`,
    createdAt: base + i * 86_400_000,
  }));
}
